--generated by https://github.com/NMRhub/database/tree/main/scripts/sak
--Python script commands.altertable from pdata.yaml
drop table if exists provenance.public_pdata;
create table provenance.public_pdata (
    provenance_track_id int not null constraint public_pdata_pk primary key generated always as identity 
); 
ALTER TABLE provenance.public_pdata add column id integer not null; 
ALTER TABLE provenance.public_pdata add column name text;
ALTER TABLE provenance.public_pdata add column state user_modifiable_text; 
ALTER TABLE provenance.public_pdata add column provenance_timestamp timestamptz not null default now();
ALTER TABLE provenance.public_pdata add column provenance_user text not null;
ALTER TABLE provenance.public_pdata add column provenance_event integer not null references provenance.sys_event_type;
